//
// Created by YongGyu Lee on 2021/02/11.
//

#ifndef STRATEGY_STRATEGY_STATIC_DUCK_INCLUDE_STATIC_DUCK_H_
#define STRATEGY_STRATEGY_STATIC_DUCK_INCLUDE_STATIC_DUCK_H_

#endif //STRATEGY_STRATEGY_STATIC_DUCK_INCLUDE_STATIC_DUCK_H_
